# The config file has the global settings of your webpage
# You need to jekyll serve again for its changes to take effect
title: PacConcept
description: Customised digital packaging solutions
author: Henriette S. Peter

# theme: jekyll-theme-startbootstrap-agency

sass:
  style: compressed

#plugins:
#  - jekyll-seo-tag

collections:
  projects:
