brand:
#  name: Pacconcept
menu-string: Menu

nav:
  #- title: Services
#    url: '#services'
#  - title: Portfolio
#    url: '#portfolio'
#  - title: About
#    url: '#about'
#  - title: Team
#    url: '#team'
#  - title: Contact
#    url: '#contact'

copyright: '&copy; Pacconcept 2019'

social-buttons:
  - icon: fab fa-linkedin-in
    url: 'https://www.linkedin.com/in/henriette-s-peter/'

quicklinks:
#  - title: Privacy Policy
#    url: '#'
#  - title: Terms of Use
#    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
