brand:
#  name: PacConcept
menu-string: Menu

nav:
  - title: Home
    url: '#page-top'
  - title: The Difference
    url: '#diff'
  - title: Services
    url: '#serv'
  - title: Benefits of Working Digital
    url: '#benefits'
  - title: about
    url: '#slogan2'
  - title: Contact
    url: '#contact'
#  - title: DE
#    url: '#DE'

copyright: '&copy; PacConcept OÜ 2021'

social-buttons:
  - icon: fab fa-linkedin-in
    url: 'https://www.linkedin.com/in/henriette-s-peter/'

quicklinks:
  - title: Impressum
    url: '/impressum/'
  - title: Privacy Policy
    url: '/privacy-policy/'
  - title: Terms and Conditions
    url: '/terms-and-conditions/'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
