brand:
#  name: PacConcept
menu-string: Menu

nav:
  - title: Home
    url: '#page-top'
  - title: Packaging Development
    url: '#packdev'
  - title: 3D Visualisation
    url: '#vis'
  - title: Production Drawing
    url: '#draw'
  - title: C-Part Management
    url: '#cpart'
  - title: about
    url: '#about'
  - title: Contact
    url: '#contact'
#  - title: DE
#    url: '#DE'

copyright: '&copy; PacConcept OÜ 2019'

social-buttons:
  - icon: fab fa-linkedin-in
    url: 'https://www.linkedin.com/in/henriette-s-peter/'

quicklinks:
  - title: Privacy Policy
    url: '/privacy-policy/'
  - title: Terms and Conditions
    url: '/terms-and-conditions/'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
